"""Render the operator's CRDs and deployment manifests for core's Zarf package.

`task operator:manifests` writes them; tests fail when the committed files are
stale, because webhook paths and RBAC follow the controller code.
"""

from dataclasses import replace
from pathlib import Path
from typing import Any

import click
import yaml

from opendefence_core import __version__
from opendefence_core.k8s_operator.app import OPERATOR_NAMESPACE, OPERATOR_TLS_SECRET, app

# Container tags can't contain "+"
IMAGE = f"ghcr.io/opendefence/core:{__version__.replace('+', '-')}"
COMMAND = ("opendefence_core", "operator")
HEALTH_PORT = 8080
HEADER = "# Generated by `task operator:manifests` from the operator code; do not edit.\n"

CRDS_PATH = Path("manifests/crds/crds.yaml")
OPERATOR_PATH = Path("manifests/operator/operator.yaml")

# cert-manager's CA injector fills in caBundle, so none is rendered
PLACEHOLDER_CA = b"-----BEGIN CERTIFICATE-----\nPLACEHOLDER\n-----END CERTIFICATE-----\n"


def _harden_deployment(deployment: dict[str, Any]) -> None:
    """Match core's API Deployment: non-root, read-only, resources, probes."""
    template = deployment["spec"]["template"]
    # The API server calls the webhook directly, outside the mesh
    template["metadata"].setdefault("annotations", {})["config.linkerd.io/skip-inbound-ports"] = "9443"
    pod = template["spec"]
    pod["securityContext"] = {
        "runAsNonRoot": True,
        "runAsUser": 65532,
        "runAsGroup": 65532,
        "seccompProfile": {"type": "RuntimeDefault"},
    }
    container = pod["containers"][0]
    container["ports"].append({"name": "health", "containerPort": HEALTH_PORT})
    container["livenessProbe"] = {"httpGet": {"path": "/healthz", "port": "health"}}
    container["resources"] = {"requests": {"cpu": "50m", "memory": "128Mi"}, "limits": {"memory": "512Mi"}}
    container["securityContext"] = {
        "allowPrivilegeEscalation": False,
        "readOnlyRootFilesystem": True,
        "capabilities": {"drop": ["ALL"]},
    }
    # The root filesystem is read-only, but cloudcoil needs a temporary directory
    container["volumeMounts"].append({"name": "tmp", "mountPath": "/tmp"})  # nosec B108
    pod["volumes"].append({"name": "tmp", "emptyDir": {}})


def _inject_ca(webhook_configuration: dict[str, Any]) -> None:
    """Let cert-manager inject the webhook CA from the operator's Certificate."""
    annotations = webhook_configuration["metadata"].setdefault("annotations", {})
    annotations["cert-manager.io/inject-ca-from"] = f"{OPERATOR_NAMESPACE}/{OPERATOR_TLS_SECRET}"
    for webhook in webhook_configuration["webhooks"]:
        webhook["clientConfig"].pop("caBundle", None)


def render() -> dict[Path, str]:
    """Return the CRD and operator manifest files keyed by repository path."""
    webhook = app.webhook
    if webhook is None:
        raise RuntimeError("The operator application has no webhook server")
    app.webhook = replace(webhook, ca_bundle=PLACEHOLDER_CA)
    try:
        documents = app.manifests(image=IMAGE, command=COMMAND)
    finally:
        app.webhook = webhook
    crds: list[dict[str, Any]] = []
    operator: list[dict[str, Any]] = []
    for document in documents:
        if document["kind"] == "CustomResourceDefinition":
            crds.append(document)
            continue
        if document["kind"] == "Deployment":
            _harden_deployment(document)
        if document["kind"] == "ValidatingWebhookConfiguration":
            _inject_ca(document)
        operator.append(document)
    return {CRDS_PATH: _dump(crds), OPERATOR_PATH: _dump(operator)}


def _dump(documents: list[dict[str, Any]]) -> str:
    """Serialize documents; Secret names are not secrets for detect-secrets."""
    text = yaml.safe_dump_all(documents, sort_keys=False, explicit_start=True)
    lines = [
        f"{line} # pragma: allowlist secret" if line.lstrip().startswith("secretName:") else line
        for line in text.splitlines()
    ]
    return HEADER + "\n".join(lines) + "\n"


@click.command()
@click.option("--check", is_flag=True, help="Exit non-zero if the committed files differ instead of writing them.")
@click.option(
    "--root",
    type=click.Path(file_okay=False, path_type=Path),
    default=Path("."),
    show_default=True,
    help="Repository root.",
)
def main(check: bool, root: Path) -> None:
    """Write (or check) manifests/crds/crds.yaml and manifests/operator/operator.yaml."""
    stale: list[str] = []
    for path, content in render().items():
        target = root / path
        if check:
            if not target.exists() or target.read_text() != content:
                stale.append(str(path))
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        click.echo(f"wrote {path}")
    if stale:
        raise click.ClickException(f"Out of date, run `task operator:manifests`: {', '.join(stale)}")


if __name__ == "__main__":
    main()
