on:
  pull_request:
  workflow_dispatch: # Allow manual triggering

jobs:
  pre_commit:
    name: Run pre-commit checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: pvarki/config-ci-library/.github/actions/setup-python@main
        with:
          python-version: "3.14"
      - name: Run pre-commit checks
        run: |
          uv run docker/pre_commit_init.sh

  bumpversion-check:
    runs-on: ubuntu-latest
    name: Validate .bumpversion.toml
    steps:
      - uses: actions/checkout@v6
      - uses: pvarki/config-ci-library/.github/actions/validate-bumpversion@main
